<a href="https://colab.research.google.com/github/Devrafael112/bigdata-enem/blob/main/big_data_apache_spark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install "pymongo[srv]"

Collecting pymongo[srv]
  Downloading pymongo-4.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (669 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 669.1/669.1 kB 8.2 MB/s eta 0:00:00
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo[srv])
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 33.9 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.6.1 pymongo-4.7.3

In [ ]:
!pip install pyspark

Collecting pyspark
  Downloading pyspark-3.5.1.tar.gz (317.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 3.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
Building wheels for collected packages: pyspark
  Building wheel for pyspark (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=25012f47e45f1f703f46ca38e1c767465fbd664229dbc66be4ea6ca4f15a23a9
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark
Installing collected packages: pyspark
Successfully installed pyspark-3.5.1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

Realizando conexão com MongoDB Atlas

In [ ]:
uri = "mongodb+srv://root:14526@enem.ogwxyhl.mongodb.net/?retryWrites=true&w=majority&appName=enem"
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))
# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

Atribuindo variáveis para o banco de dados e coleção

In [ ]:
db = client["enem"]
collection = db["microdados"]

Lendo coleção e atribuindo à um dataframe

In [ ]:
def read_data_from_collection(collection):
    cursor = collection.find()
    df = pd.DataFrame(list(cursor))
    return df

# Lendo todos os documentos da coleção
df = read_data_from_collection(collection)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263999 entries, 0 to 263998
Data columns (total 78 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   _id                     263999 non-null  object
 1                           263999 non-null  int64
 2   NU_INSCRICAO            263999 non-null  int64
 3   NU_ANO                  263999 non-null  int64
 4   TP_FAIXA_ETARIA         263999 non-null  int64
 5   TP_SEXO                 263999 non-null  object
 6   TP_ESTADO_CIVIL         263999 non-null  int64
 7   TP_COR_RACA             263999 non-null  int64
 8   TP_NACIONALIDADE        263999 non-null  int64
 9   TP_ST_CONCLUSAO         263999 non-null  int64
 10  TP_ANO_CONCLUIU         263999 non-null  int64
 11  TP_ESCOLA               263999 non-null  int64
 12  IN_TREINEIRO            263999 non-null  int64
 13  CO_MUNICIPIO_PROVA      263999 non-null  int64
 14  NO_MUNICIPIO_PROVA      263999 non-null  object
 15  CO_UF_PROVA             263999 non-null  int64
 16  SG_UF_PROVA             263999 non-null  object
 17  TP_PRESENCA_CN          263999 non-null  int64
 18  TP_PRESENCA_CH          263999 non-null  int64
 19  TP_PRESENCA_LC          263999 non-null  int64
 20  TP_PRESENCA_MT          263999 non-null  int64
 21  CO_PROVA_CH             214040 non-null  float64
 22  CO_PROVA_LC             214040 non-null  float64
 23  NU_NOTA_CH              214040 non-null  float64
 24  NU_NOTA_LC              214040 non-null  float64
 25  TX_RESPOSTAS_CH         214040 non-null  object
 26  TX_RESPOSTAS_LC         214040 non-null  object
 27  TP_LINGUA               263999 non-null  int64
 28  TX_GABARITO_CH          214040 non-null  object
 29  TX_GABARITO_LC          214040 non-null  object
 30  TP_STATUS_REDACAO       214040 non-null  float64
 31  NU_NOTA_COMP1           214040 non-null  float64
 32  NU_NOTA_COMP2           214040 non-null  float64
 33  NU_NOTA_COMP3           214040 non-null  float64
 34  NU_NOTA_COMP4           214040 non-null  float64
 35  NU_NOTA_COMP5           214040 non-null  float64
 36  NU_NOTA_REDACAO         214040 non-null  float64
 37  Q001                    263999 non-null  object
 38  Q002                    263999 non-null  object
 39  Q003                    263999 non-null  object
 40  Q004                    263999 non-null  object
 41  Q005                    263999 non-null  float64
 42  Q006                    263999 non-null  object
 43  Q007                    263999 non-null  object
 44  Q008                    263999 non-null  object
 45  Q009                    263999 non-null  object
 46  Q010                    263999 non-null  object
 47  Q011                    263999 non-null  object
 48  Q012                    263999 non-null  object
 49  Q013                    263999 non-null  object
 50  Q014                    263999 non-null  object
 51  Q015                    263999 non-null  object
 52  Q016                    263999 non-null  object
 53  Q017                    263999 non-null  object
 54  Q018                    263999 non-null  object
 55  Q019                    263999 non-null  object
 56  Q020                    263999 non-null  object
 57  Q021                    263999 non-null  object
 58  Q022                    263999 non-null  object
 59  Q023                    263999 non-null  object
 60  Q024                    263999 non-null  object
 61  Q025                    263999 non-null  object
 62  CO_PROVA_CN             205124 non-null  float64
 63  CO_PROVA_MT             205124 non-null  float64
 64  NU_NOTA_CN              205124 non-null  float64
 65  NU_NOTA_MT              205124 non-null  float64
 66  TX_RESPOSTAS_CN         205124 non-null  object
 67  TX_RESPOSTAS_MT         205124 non-null  object
 68  TX_GABARITO_CN          205124 non-null  object
 69  TX_GABARITO_MT          205124 non-null  object
 70  TP_ENSINO               121236 non-null  float64
 71  CO_MUNICIPIO_ESC        78929 non-null   float64
 72  NO_MUNICIPIO_ESC        78929 non-null   object
 73  CO_UF_ESC               78929 non-null   float64
 74  SG_UF_ESC               78929 non-null   object
 75  TP_DEPENDENCIA_ADM_ESC  78929 non-null   float64
 76  TP_LOCALIZACAO_ESC      78929 non-null   float64
 77  TP_SIT_FUNC_ESC         78929 non-null   float64
dtypes: float64(22), int64(18), object(38)
memory usage: 157.1+ MB

In [ ]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("SparkBigdata").getOrCreate()

Convertendo dataframe pandas para apache spark e as colunas do tipo objetc para string

In [ ]:
import pyspark.sql.functions as F
from pyspark.sql.types import StringType

df['_id'] = df['_id'].astype(str)

spark_df = spark.createDataFrame(df)

In [ ]:
spark_df.show(5)

+--------------------+---+------------+------+---------------+-------+---------------+-----------+----------------+---------------+---------------+---------+------------+------------------+--------------------+-----------+-----------+--------------+--------------+--------------+--------------+-----------+-----------+----------+----------+--------------------+--------------------+---------+--------------------+--------------------+-----------------+-------------+-------------+-------------+-------------+-------------+---------------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----------+-----------+----------+----------+--------------------+--------------------+--------------------+--------------------+---------+----------------+----------------+---------+---------+----------------------+------------------+---------------+
|                 _id|   |NU_INSCRICAO|NU_ANO|TP_FAIXA_ETARIA|TP_SEXO|TP_ESTADO_CIVIL|TP_COR_RACA|TP_NACIONALIDADE|TP_ST_CONCLUSAO|TP_ANO_CONCLUIU|TP_ESCOLA|IN_TREINEIRO|CO_MUNICIPIO_PROVA|  NO_MUNICIPIO_PROVA|CO_UF_PROVA|SG_UF_PROVA|TP_PRESENCA_CN|TP_PRESENCA_CH|TP_PRESENCA_LC|TP_PRESENCA_MT|CO_PROVA_CH|CO_PROVA_LC|NU_NOTA_CH|NU_NOTA_LC|     TX_RESPOSTAS_CH|     TX_RESPOSTAS_LC|TP_LINGUA|      TX_GABARITO_CH|      TX_GABARITO_LC|TP_STATUS_REDACAO|NU_NOTA_COMP1|NU_NOTA_COMP2|NU_NOTA_COMP3|NU_NOTA_COMP4|NU_NOTA_COMP5|NU_NOTA_REDACAO|Q001|Q002|Q003|Q004|Q005|Q006|Q007|Q008|Q009|Q010|Q011|Q012|Q013|Q014|Q015|Q016|Q017|Q018|Q019|Q020|Q021|Q022|Q023|Q024|Q025|CO_PROVA_CN|CO_PROVA_MT|NU_NOTA_CN|NU_NOTA_MT|     TX_RESPOSTAS_CN|     TX_RESPOSTAS_MT|      TX_GABARITO_CN|      TX_GABARITO_MT|TP_ENSINO|CO_MUNICIPIO_ESC|NO_MUNICIPIO_ESC|CO_UF_ESC|SG_UF_ESC|TP_DEPENDENCIA_ADM_ESC|TP_LOCALIZACAO_ESC|TP_SIT_FUNC_ESC|
+--------------------+---+------------+------+---------------+-------+---------------+-----------+----------------+---------------+---------------+---------+------------+------------------+--------------------+-----------+-----------+--------------+--------------+--------------+--------------+-----------+-----------+----------+----------+--------------------+--------------------+---------+--------------------+--------------------+-----------------+-------------+-------------+-------------+-------------+-------------+---------------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----------+-----------+----------+----------+--------------------+--------------------+--------------------+--------------------+---------+----------------+----------------+---------+---------+----------------------+------------------+---------------+
|666494a8a8908b2f9...|  0|210053865474|  2021|              5|      F|              1|          1|               1|              1|              3|        1|           0|           3144805|           Nova Lima|         31|         MG|             0|             1|             1|             0|      881.0|      892.0|     574.6|     472.6|BBCCECEABCEABADDA...|99999BADDEAEBACAD...|        1|BEECCAEABADBCAEBA...|ABBACAAECACDBDDAD...|              1.0|        140.0|        120.0|        120.0|        180.0|        200.0|          760.0|   F|   F|   B|   B| 3.0|   D|   A|   B|   C|   B|   A|   B|   A|   B|   A|   A|   A|   A|   B|   A|   A|   B|   A|   B|   B|        NaN|        NaN|       NaN|       NaN|                 NaN|                 NaN|                 NaN|                 NaN|      NaN|             NaN|             NaN|      NaN|      NaN|                   NaN|               NaN|            NaN|
|666494a8a8908b2f9...|  1|210052384164|  2021|             12|      M|              1|          1|               1|              1|             11|        1|           0|           2704302|              Maceió|         27|         AL|             1|             1|             1|             1|      882.0|      891.0|     551.8|     498.3|ECCDAAEBCDACBDBDE...|99999ACECCEEBACDA...|        1|EBAAEADBCACBBABEE...|ACABBACAEADCEADAB...|              1.0|        120.0|        120.0|        120.0|        120.0|         80.0|          560.0|   B|   B|   B|   B| 3.0|   B|   A|   B|   C|   A|   A|   B|   A|   A|   A|   A|   A|   A|   B|   A|   A|   C|   A|   A|   A|      912.0|      901.0|     505.9|     461.5|DCBCCBDBCCCCCCDDC...|CDCCBCCCDCCCCBEAC...|DABCEDEBEEBBCABED...|DCCAEBABDDCABEECC...|      NaN|             NaN|             NaN|      NaN|      NaN|                   NaN|               NaN|            NaN|
|666494a8a8908b2f9...|  2|210052589243|  2021|             13|      F|              3|          1|               1|              1|             15|        1|           0|           3515707|Ferraz de Vasconc...|         35|         SP|             0|             0|             0|             0|        NaN|        NaN|       NaN|       NaN|                 NaN|                 NaN|        1|                 NaN|                 NaN|              NaN|          NaN|          NaN|          NaN|          NaN|          NaN|            NaN|   B|   C|   C|   B| 3.0|   C|   A|   B|   B|   A|   A|   B|   B|   A|   A|   B|   A|   A|   B|   A|   A|   C|   B|   B|   B|        NaN|        NaN|       NaN|       NaN|                 NaN|                 NaN|                 NaN|                 NaN|      NaN|             NaN|             NaN|      NaN|      NaN|                   NaN|               NaN|            NaN|
|666494a8a8908b2f9...|  3|210052128335|  2021|              3|      M|              1|          3|               1|              2|              0|        2|           0|           2304202|               Crato|         23|         CE|             1|             1|             1|             1|      880.0|      890.0|     678.9|     638.9|CBBDABAABBAAEECEB...|ABBCA99999CDECCCB...|        0|BBBAAEECBBABEECEB...|ABBCAEAACADDCACDC...|              1.0|        120.0|        180.0|        120.0|        200.0|        160.0|          780.0|   B|   B|   B|   B| 6.0|   B|   A|   B|   C|   A|   A|   B|   A|   A|   A|   A|   A|   A|   B|   A|   A|   B|   A|   B|   B|      911.0|      902.0|     580.7|     659.5|CCABBDAEDBEBEDDCA...|EACDCEACDDDDCBDDC...|CDBBBCABEDEDEAAEB...|ECCCABBDBDDDCEDDC...|      1.0|       2304202.0|           Crato|     23.0|       CE|                   2.0|               1.0|            1.0|
|666494a8a8908b2f9...|  4|210051353021|  2021|              2|      F|              1|          3|               1|              2|              0|        2|           0|           2300150|             Acarape|         23|         CE|             1|             1|             1|             1|      882.0|      891.0|     532.4|     457.6|CAE.ACDCAAEBBEDEB...|99999EAACBDCBECCA...|        1|EBAAEADBCACBBABEE...|ACABBACAEADCEADAB...|              1.0|        120.0|        140.0|        160.0|        180.0|        180.0|          780.0|   D|   E|   F|   D| 4.0|   C|   A|   B|   C|   A|   A|   B|   A|   B|   A|   B|   A|   A|   B|   A|   B|   E|   A|   B|   B|      912.0|      901.0|     497.7|     582.6|BABCDCCBEBCD.DEDC...|ACEDEBECABDABDEEC...|DABCEDEBEEBBCABED...|DCCAEBABDDCABEECC...|      1.0|       2311603.0|        Redenção|     23.0|       CE|                   2.0|               1.0|            1.0|
+--------------------+---+------------+------+---------------+-------+---------------+-----------+----------------+---------------+---------------+---------+------------+------------------+--------------------+-----------+-----------+--------------+--------------+--------------+--------------+-----------+-----------+----------+----------+--------------------+--------------------+---------+--------------------+--------------------+-----------------+-------------+-------------+-------------+-------------+-------------+---------------+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+----+-----------+-----------+----------+----------+--------------------+--------------------+--------------------+--------------------+---------+----------------+----------------+---------+---------+----------------------+------------------+---------------+
only showing top 5 rows

In [ ]:
spark_df.printSchema()

root
 |-- _id: string (nullable = true)
 |-- : long (nullable = true)
 |-- NU_INSCRICAO: long (nullable = true)
 |-- NU_ANO: long (nullable = true)
 |-- TP_FAIXA_ETARIA: long (nullable = true)
 |-- TP_SEXO: string (nullable = true)
 |-- TP_ESTADO_CIVIL: long (nullable = true)
 |-- TP_COR_RACA: long (nullable = true)
 |-- TP_NACIONALIDADE: long (nullable = true)
 |-- TP_ST_CONCLUSAO: long (nullable = true)
 |-- TP_ANO_CONCLUIU: long (nullable = true)
 |-- TP_ESCOLA: long (nullable = true)
 |-- IN_TREINEIRO: long (nullable = true)
 |-- CO_MUNICIPIO_PROVA: long (nullable = true)
 |-- NO_MUNICIPIO_PROVA: string (nullable = true)
 |-- CO_UF_PROVA: long (nullable = true)
 |-- SG_UF_PROVA: string (nullable = true)
 |-- TP_PRESENCA_CN: long (nullable = true)
 |-- TP_PRESENCA_CH: long (nullable = true)
 |-- TP_PRESENCA_LC: long (nullable = true)
 |-- TP_PRESENCA_MT: long (nullable = true)
 |-- CO_PROVA_CH: double (nullable = true)
 |-- CO_PROVA_LC: double (nullable = true)
 |-- NU_NOTA_CH: double (nullable = true)
 |-- NU_NOTA_LC: double (nullable = true)
 |-- TX_RESPOSTAS_CH: string (nullable = true)
 |-- TX_RESPOSTAS_LC: string (nullable = true)
 |-- TP_LINGUA: long (nullable = true)
 |-- TX_GABARITO_CH: string (nullable = true)
 |-- TX_GABARITO_LC: string (nullable = true)
 |-- TP_STATUS_REDACAO: double (nullable = true)
 |-- NU_NOTA_COMP1: double (nullable = true)
 |-- NU_NOTA_COMP2: double (nullable = true)
 |-- NU_NOTA_COMP3: double (nullable = true)
 |-- NU_NOTA_COMP4: double (nullable = true)
 |-- NU_NOTA_COMP5: double (nullable = true)
 |-- NU_NOTA_REDACAO: double (nullable = true)
 |-- Q001: string (nullable = true)
 |-- Q002: string (nullable = true)
 |-- Q003: string (nullable = true)
 |-- Q004: string (nullable = true)
 |-- Q005: double (nullable = true)
 |-- Q006: string (nullable = true)
 |-- Q007: string (nullable = true)
 |-- Q008: string (nullable = true)
 |-- Q009: string (nullable = true)
 |-- Q010: string (nullable = true)
 |-- Q011: string (nullable = true)
 |-- Q012: string (nullable = true)
 |-- Q013: string (nullable = true)
 |-- Q014: string (nullable = true)
 |-- Q015: string (nullable = true)
 |-- Q016: string (nullable = true)
 |-- Q017: string (nullable = true)
 |-- Q018: string (nullable = true)
 |-- Q019: string (nullable = true)
 |-- Q020: string (nullable = true)
 |-- Q021: string (nullable = true)
 |-- Q022: string (nullable = true)
 |-- Q023: string (nullable = true)
 |-- Q024: string (nullable = true)
 |-- Q025: string (nullable = true)
 |-- CO_PROVA_CN: double (nullable = true)
 |-- CO_PROVA_MT: double (nullable = true)
 |-- NU_NOTA_CN: double (nullable = true)
 |-- NU_NOTA_MT: double (nullable = true)
 |-- TX_RESPOSTAS_CN: string (nullable = true)
 |-- TX_RESPOSTAS_MT: string (nullable = true)
 |-- TX_GABARITO_CN: string (nullable = true)
 |-- TX_GABARITO_MT: string (nullable = true)
 |-- TP_ENSINO: double (nullable = true)
 |-- CO_MUNICIPIO_ESC: double (nullable = true)
 |-- NO_MUNICIPIO_ESC: string (nullable = true)
 |-- CO_UF_ESC: double (nullable = true)
 |-- SG_UF_ESC: string (nullable = true)
 |-- TP_DEPENDENCIA_ADM_ESC: double (nullable = true)
 |-- TP_LOCALIZACAO_ESC: double (nullable = true)
 |-- TP_SIT_FUNC_ESC: double (nullable = true)

In [ ]:
numeric_features = [t[0] for t in spark_df.dtypes if t[1] == 'int']
spark_df.select(numeric_features).describe().toPandas().transpose()
numeric_features = [t[0] for t in spark_df.dtypes if t[1] == 'int' or t[1] == 'double']
numeric_df = spark_df.select(numeric_features).toPandas()
numeric_df.corr()

,CO_PROVA_CH,CO_PROVA_LC,NU_NOTA_CH,NU_NOTA_LC,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,...,CO_PROVA_CN,CO_PROVA_MT,NU_NOTA_CN,NU_NOTA_MT,TP_ENSINO,CO_MUNICIPIO_ESC,CO_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC
CO_PROVA_CH,1.000000,0.999475,-0.000616,-0.007899,0.001583,-0.036685,-0.055257,-0.046417,-0.056559,-0.068234,...,0.994624,0.993792,-0.006716,-0.013943,0.017432,0.051373,0.051114,0.020835,-0.024824,0.007316
CO_PROVA_LC,0.999475,1.000000,-0.000387,-0.008164,0.001580,-0.036653,-0.055219,-0.046503,-0.056506,-0.068199,...,0.992580,0.992349,-0.006983,-0.014283,0.017403,0.051397,0.051138,0.020683,-0.024671,0.007286
NU_NOTA_CH,-0.000616,-0.000387,1.000000,0.767371,-0.135724,0.480676,0.447330,0.484738,0.476682,0.478123,...,0.004381,0.004388,0.693531,0.648992,-0.036281,0.082450,0.080709,0.252711,-0.050147,0.018530
NU_NOTA_LC,-0.007899,-0.008164,0.767371,1.000000,-0.148148,0.509472,0.452109,0.494190,0.483212,0.489970,...,-0.003145,-0.003320,0.677987,0.646834,-0.039761,0.092725,0.090828,0.262516,-0.056695,0.015280
TP_STATUS_REDACAO,0.001583,0.001580,-0.135724,-0.148148,1.000000,-0.567034,-0.487641,-0.504904,-0.523389,-0.314485,...,-0.001284,-0.001157,-0.093876,-0.092206,0.007643,-0.042868,-0.042343,-0.059804,0.030726,-0.009279
NU_NOTA_COMP1,-0.036685,-0.036653,0.480676,0.509472,-0.567034,1.000000,0.710746,0.798272,0.816891,0.634271,...,-0.034642,-0.034820,0.446851,0.466078,-0.031778,0.046051,0.044832,0.232978,-0.053974,0.020106
NU_NOTA_COMP2,-0.055257,-0.055219,0.447330,0.452109,-0.487641,0.710746,1.000000,0.805182,0.773191,0.701610,...,-0.053344,-0.053472,0.411628,0.430771,-0.025157,0.013193,0.012135,0.214657,-0.045617,0.024401
NU_NOTA_COMP3,-0.046417,-0.046503,0.484738,0.494190,-0.504904,0.798272,0.805182,1.000000,0.834624,0.712944,...,-0.044801,-0.044985,0.461671,0.474673,-0.027965,0.010435,0.009450,0.231081,-0.047796,0.020659
NU_NOTA_COMP4,-0.056559,-0.056506,0.476682,0.483212,-0.523389,0.816891,0.773191,0.834624,1.000000,0.718908,...,-0.054909,-0.055045,0.456762,0.479305,-0.029028,0.008745,0.007796,0.250432,-0.050904,0.023810
NU_NOTA_COMP5,-0.068234,-0.068199,0.478123,0.489970,-0.314485,0.634271,0.701610,0.712944,0.718908,1.000000,...,-0.065892,-0.065856,0.442054,0.457488,-0.027569,-0.010050,-0.011071,0.233427,-0.045770,0.019651
NU_NOTA_REDACAO,-0.061409,-0.061389,0.530370,0.543364,-0.517124,0.861957,0.894227,0.916264,0.916179,0.874552,...,-0.059602,-0.059715,0.498742,0.518686,-0.031466,0.011829,0.010669,0.258723,-0.053853,0.024153
Q005,-0.041137,-0.041031,-0.090460,-0.088851,0.015537,-0.054445,-0.037301,-0.041893,-0.040417,-0.038894,...,-0.040134,-0.040094,-0.080867,-0.067691,0.003488,-0.075881,-0.075418,-0.056840,0.024469,-0.004017
CO_PROVA_CN,0.994624,0.992580,0.004381,-0.003145,-0.001284,-0.034642,-0.053344,-0.044801,-0.054909,-0.065892,...,1.000000,0.999316,-0.005988,-0.013540,0.016790,0.050175,0.049915,0.021508,-0.023559,0.006842
CO_PROVA_MT,0.993792,0.992349,0.004388,-0.003320,-0.001157,-0.034820,-0.053472,-0.044985,-0.055045,-0.065856,...,0.999316,1.000000,-0.006283,-0.014142,0.016637,0.050280,0.050020,0.021554,-0.023362,0.006682
NU_NOTA_CN,-0.006716,-0.006983,0.693531,0.677987,-0.093876,0.446851,0.411628,0.461671,0.456762,0.442054,...,-0.005988,-0.006283,1.000000,0.690798,-0.032002,0.082589,0.080892,0.295554,-0.041428,0.018738
NU_NOTA_MT,-0.013943,-0.014283,0.648992,0.646834,-0.092206,0.466078,0.430771,0.474673,0.479305,0.457488,...,-0.013540,-0.014142,0.690798,1.000000,-0.034712,0.085208,0.083290,0.295316,-0.045294,0.019294
TP_ENSINO,0.017432,0.017403,-0.036281,-0.039761,0.007643,-0.031778,-0.025157,-0.027965,-0.029028,-0.027569,...,0.016790,0.016637,-0.032002,-0.034712,1.000000,0.003564,0.003675,-0.023208,-0.002050,-0.002598
CO_MUNICIPIO_ESC,0.051373,0.051397,0.082450,0.092725,-0.042868,0.046051,0.013193,0.010435,0.008745,-0.010050,...,0.050175,0.050280,0.082589,0.085208,0.003564,1.000000,0.999914,0.043885,-0.046071,-0.014241
CO_UF_ESC,0.051114,0.051138,0.080709,0.090828,-0.042343,0.044832,0.012135,0.009450,0.007796,-0.011071,...,0.049915,0.050020,0.080892,0.083290,0.003675,0.999914,1.000000,0.042293,-0.045768,-0.014327
TP_DEPENDENCIA_ADM_ESC,0.020835,0.020683,0.252711,0.262516,-0.059804,0.232978,0.214657,0.231081,0.250432,0.233427,...,0.021508,0.021554,0.295554,0.295316,-0.023208,0.043885,0.042293,1.000000,-0.093240,0.059830
TP_LOCALIZACAO_ESC,-0.024824,-0.024671,-0.050147,-0.056695,0.030726,-0.053974,-0.045617,-0.047796,-0.050904,-0.045770,...,-0.023559,-0.023362,-0.041428,-0.045294,-0.002050,-0.046071,-0.045768,-0.093240,1.000000,0.017426
TP_SIT_FUNC_ESC,0.007316,0.007286,0.018530,0.015280,-0.009279,0.020106,0.024401,0.020659,0.023810,0.019651,...,0.006842,0.006682,0.018738,0.019294,-0.002598,-0.014241,-0.014327,0.059830,0.017426,1.000000

In [ ]:
df.head(5)

,_id,,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,...,TX_GABARITO_CN,TX_GABARITO_MT,TP_ENSINO,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC
0,666494a8a8908b2f9270fd44,0,210053865474,2021,5,F,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,666494a8a8908b2f9270fd45,1,210052384164,2021,12,M,1,1,1,1,...,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,666494a8a8908b2f9270fd46,2,210052589243,2021,13,F,3,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,666494a8a8908b2f9270fd47,3,210052128335,2021,3,M,1,3,1,2,...,CDBBBCABEDEDEAAEBACCCBDABCDCBCBDECDADCDBBEEBB,ECCCABBDBDDDCEDDCABXEEEBABEDCEDCCAEBADBCCECDA,1.0,2304202.0,Crato,23.0,CE,2.0,1.0,1.0
4,666494a8a8908b2f9270fd48,4,210051353021,2021,2,F,1,3,1,2,...,DABCEDEBEEBBCABEDDCBCBECDADCDAACBDCCCDBBBEBAB,DCCAEBABDDCABEECCBCCEXADDCEECDEBADCABBDBDEDCE,1.0,2311603.0,Redenção,23.0,CE,2.0,1.0,1.0

Realizando limpeza do datraframe <br>Selecionando as colunas mais relevantes

In [ ]:
df_limpo = df[['TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA','TP_NACIONALIDADE','TP_ST_CONCLUSAO','TP_ANO_CONCLUIU','TP_ESCOLA','TP_ENSINO','IN_TREINEIRO','NO_MUNICIPIO_PROVA','SG_UF_PROVA','TP_PRESENCA_CN','TP_PRESENCA_CH','TP_PRESENCA_LC','TP_PRESENCA_MT','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT','NU_NOTA_REDACAO']]

In [ ]:
df_limpo.head(5)

,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,TP_ENSINO,IN_TREINEIRO,NO_MUNICIPIO_PROVA,SG_UF_PROVA,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO
0,5,F,1,1,1,1,3,1,NaN,0,Nova Lima,MG,0,1,1,0,574.6,472.6,NaN,760.0
1,12,M,1,1,1,1,11,1,NaN,0,Maceió,AL,1,1,1,1,551.8,498.3,461.5,560.0
2,13,F,3,1,1,1,15,1,NaN,0,Ferraz de Vasconcelos,SP,0,0,0,0,NaN,NaN,NaN,NaN
3,3,M,1,3,1,2,0,2,1.0,0,Crato,CE,1,1,1,1,678.9,638.9,659.5,780.0
4,2,F,1,3,1,2,0,2,1.0,0,Acarape,CE,1,1,1,1,532.4,457.6,582.6,780.0

Reatribuindo o dataframe desta vez limpo ao spark

In [ ]:
spark_df = spark.createDataFrame(df_limpo)

In [ ]:
# Estatísticas descritivas das colunas selecionadas
spark_df.describe().show()

+-------+------------------+-------+-------------------+------------------+------------------+------------------+------------------+------------------+---------+------------------+------------------+-----------+------------------+-------------------+-------------------+------------------+----------+----------+----------+---------------+
|summary|   TP_FAIXA_ETARIA|TP_SEXO|    TP_ESTADO_CIVIL|       TP_COR_RACA|  TP_NACIONALIDADE|   TP_ST_CONCLUSAO|   TP_ANO_CONCLUIU|         TP_ESCOLA|TP_ENSINO|      IN_TREINEIRO|NO_MUNICIPIO_PROVA|SG_UF_PROVA|    TP_PRESENCA_CN|     TP_PRESENCA_CH|     TP_PRESENCA_LC|    TP_PRESENCA_MT|NU_NOTA_CH|NU_NOTA_LC|NU_NOTA_MT|NU_NOTA_REDACAO|
+-------+------------------+-------+-------------------+------------------+------------------+------------------+------------------+------------------+---------+------------------+------------------+-----------+------------------+-------------------+-------------------+------------------+----------+----------+----------+---------------+
|  count|            263999| 263999|             263999|            263999|            263999|            263999|            263999|            263999|   263999|            263999|            263999|     263999|            263999|             263999|             263999|            263999|    263999|    263999|    263999|         263999|
|   mean|  4.28384198424994|   NULL| 1.0199659847196392|2.0922730767919577|1.0277198019689469|1.6858169917310293|1.5589945416459912|1.5288315486043507|      NaN|0.1025685703354937|              NULL|       NULL|0.7778287038966056| 0.8130788374198387| 0.8130788374198387|0.7778287038966056|       NaN|       NaN|       NaN|            NaN|
| stddev|3.1250285552387167|   NULL|0.33484496376796113|1.0162883552219877| 0.199461643414234|0.6584395914847319| 3.241602177913016|0.5986696598801927|      NaN|0.3033951340827901|              NULL|       NULL| 0.416716667947772|0.39281091715039923|0.39281091715039923| 0.416716667947772|       NaN|       NaN|       NaN|            NaN|
|    min|                 1|      F|                  0|                 0|                 0|                 1|                 0|                 1|      1.0|                 0|        Abaetetuba|         AC|                 0|                  0|                  0|                 0|       0.0|       0.0|       0.0|            0.0|
|    max|                20|      M|                  4|                 5|                 4|                 4|                15|                 3|      NaN|                 1|            Óbidos|         TO|                 2|                  2|                  2|                 2|       NaN|       NaN|       NaN|            NaN|
+-------+------------------+-------+-------------------+------------------+------------------+------------------+------------------+------------------+---------+------------------+------------------+-----------+------------------+-------------------+-------------------+------------------+----------+----------+----------+---------------+

In [ ]:
# Contar registros por sexo
spark_df.groupBy("TP_SEXO").count().show()

+-------+------+
|TP_SEXO| count|
+-------+------+
|      F|184204|
|      M| 79795|
+-------+------+

In [ ]:
# Contar valores não nulos para cada coluna de nota
spark_df.select([count(when(col(c).isNotNull(), c)).alias(c) for c in ['NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']]).show()

+----------+----------+----------+---------------+
|NU_NOTA_CH|NU_NOTA_LC|NU_NOTA_MT|NU_NOTA_REDACAO|
+----------+----------+----------+---------------+
|    263999|    263999|    263999|         263999|
+----------+----------+----------+---------------+

In [ ]:
# Contar valores não numéricos (ou nulos) nas colunas de notas
non_numeric_counts = spark_df.select([
    count(when(~col(c).cast("double").isNotNull(), c)).alias(c)
    for c in ['NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO']
])
non_numeric_counts.show()

+----------+----------+----------+---------------+
|NU_NOTA_CH|NU_NOTA_LC|NU_NOTA_MT|NU_NOTA_REDACAO|
+----------+----------+----------+---------------+
|         0|         0|         0|              0|
+----------+----------+----------+---------------+

In [ ]:
# Converter colunas de notas para tipo double
spark_df = spark_df.withColumn("NU_NOTA_CH", col("NU_NOTA_CH").cast("double"))
spark_df = spark_df.withColumn("NU_NOTA_LC", col("NU_NOTA_LC").cast("double"))
spark_df = spark_df.withColumn("NU_NOTA_MT", col("NU_NOTA_MT").cast("double"))
spark_df = spark_df.withColumn("NU_NOTA_REDACAO", col("NU_NOTA_REDACAO").cast("double"))

# Verificar se a conversão foi bem-sucedida
spark_df.printSchema()

root
 |-- TP_FAIXA_ETARIA: long (nullable = true)
 |-- TP_SEXO: string (nullable = true)
 |-- TP_ESTADO_CIVIL: long (nullable = true)
 |-- TP_COR_RACA: long (nullable = true)
 |-- TP_NACIONALIDADE: long (nullable = true)
 |-- TP_ST_CONCLUSAO: long (nullable = true)
 |-- TP_ANO_CONCLUIU: long (nullable = true)
 |-- TP_ESCOLA: long (nullable = true)
 |-- TP_ENSINO: double (nullable = true)
 |-- IN_TREINEIRO: long (nullable = true)
 |-- NO_MUNICIPIO_PROVA: string (nullable = true)
 |-- SG_UF_PROVA: string (nullable = true)
 |-- TP_PRESENCA_CN: long (nullable = true)
 |-- TP_PRESENCA_CH: long (nullable = true)
 |-- TP_PRESENCA_LC: long (nullable = true)
 |-- TP_PRESENCA_MT: long (nullable = true)
 |-- NU_NOTA_CH: double (nullable = true)
 |-- NU_NOTA_LC: double (nullable = true)
 |-- NU_NOTA_MT: double (nullable = true)
 |-- NU_NOTA_REDACAO: double (nullable = true)

In [ ]:
# Remover linhas onde qualquer coluna de nota tem valor ausente
spark_df_clean = spark_df.dropna(subset=['NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT', 'NU_NOTA_REDACAO'])

In [ ]:
from pyspark.sql.functions import avg

# Médias das notas por sexo após limpeza dos dados
df_medias_sexo_clean = spark_df_clean.groupBy("TP_SEXO").agg(
    avg("NU_NOTA_CH").alias("Media_Nota_CH"),
    avg("NU_NOTA_LC").alias("Media_Nota_LC"),
    avg("NU_NOTA_MT").alias("Media_Nota_MT"),
    avg("NU_NOTA_REDACAO").alias("Media_Nota_REDACAO")
)

df_medias_sexo_clean.show()

+-------+-----------------+-----------------+-----------------+------------------+
|TP_SEXO|    Media_Nota_CH|    Media_Nota_LC|    Media_Nota_MT|Media_Nota_REDACAO|
+-------+-----------------+-----------------+-----------------+------------------+
|      F|519.6173580755641|503.1722192833461|522.5361715900552| 663.3679037781552|
|      M|536.0376563474589| 509.287676044781|557.8751616821503| 638.1799678277141|
+-------+-----------------+-----------------+-----------------+------------------+

In [ ]:
from pyspark.sql.functions import round

df_medias_faixa_etaria = spark_df_clean.groupBy("TP_FAIXA_ETARIA").agg(
    round(avg("NU_NOTA_CH"), 2).alias("Media_Nota_CH"),
    round(avg("NU_NOTA_LC"), 2).alias("Media_Nota_LC"),
    round(avg("NU_NOTA_MT"), 2).alias("Media_Nota_MT"),
    round(avg("NU_NOTA_REDACAO"), 2).alias("Media_Nota_REDACAO")
)

df_medias_faixa_etaria.show()

+---------------+-------------+-------------+-------------+------------------+
|TP_FAIXA_ETARIA|Media_Nota_CH|Media_Nota_LC|Media_Nota_MT|Media_Nota_REDACAO|
+---------------+-------------+-------------+-------------+------------------+
|             19|       519.31|       427.41|       457.16|             570.0|
|              7|       537.18|       510.64|       542.95|            663.36|
|              6|       534.38|       509.08|       541.52|            670.77|
|              9|       539.64|       509.27|       539.33|             650.5|
|             17|       538.08|       470.82|       487.71|            509.51|
|              5|       529.12|        506.6|       538.51|            671.88|
|              1|        511.8|       501.28|       530.01|            642.37|
|             10|       541.84|       511.92|       537.42|            642.29|
|              3|       520.41|        503.4|       529.65|            657.87|
|             12|       545.17|       503.72|       522.73|            591.51|
|              8|       541.73|       512.85|       542.32|            654.58|
|             11|       548.37|       513.83|       535.91|            629.91|
|              2|       521.88|       506.64|       535.64|            661.14|
|              4|       524.56|       504.98|       534.79|            667.38|
|             13|       540.16|       490.63|        507.2|            569.21|
|             18|       532.34|        472.3|       483.92|            514.88|
|             14|       531.55|       477.81|       495.99|            541.83|
|             15|       522.62|       464.64|       479.86|            518.29|
|             20|        498.7|       428.19|        449.5|            461.43|
|             16|       527.72|       465.42|       487.89|             512.7|
+---------------+-------------+-------------+-------------+------------------+

In [ ]:
df_medias_estado = spark_df_clean.groupBy("SG_UF_PROVA").agg(
    round(avg("NU_NOTA_CH"), 2).alias("Media_Nota_CH"),
    round(avg("NU_NOTA_LC"), 2).alias("Media_Nota_LC"),
    round(avg("NU_NOTA_MT"), 2).alias("Media_Nota_MT"),
    round(avg("NU_NOTA_REDACAO"), 2).alias("Media_Nota_REDACAO")
)

df_medias_estado.show()

+-----------+-------------+-------------+-------------+------------------+
|SG_UF_PROVA|Media_Nota_CH|Media_Nota_LC|Media_Nota_MT|Media_Nota_REDACAO|
+-----------+-------------+-------------+-------------+------------------+
|         SC|       551.88|       525.96|       563.71|            676.31|
|         RO|       512.28|       492.63|       520.18|            648.86|
|         PI|       505.61|       487.01|       516.26|            662.16|
|         AM|       493.87|       478.65|       488.98|            584.63|
|         RR|       518.63|       497.98|       520.81|            644.74|
|         GO|        504.3|       488.83|       509.47|            608.98|
|         TO|       503.35|       484.83|        506.7|            636.82|
|         MT|       522.01|       498.38|       530.58|            651.57|
|         SP|       557.84|       536.99|       571.69|            679.23|
|         PB|       511.59|       490.28|        520.6|            661.63|
|         ES|       541.97|       520.69|       556.57|            678.47|
|         RS|       552.32|       530.05|       562.14|            689.44|
|         MS|       521.56|       504.99|       534.27|            650.78|
|         AL|       509.35|       489.86|       518.85|            661.64|
|         MG|       555.66|       530.81|       574.47|            710.58|
|         PA|       500.48|       477.03|       496.81|            641.41|
|         BA|       511.97|       492.31|       513.27|            645.93|
|         SE|       512.92|        492.1|       519.46|            670.23|
|         PE|       512.31|       497.37|       526.99|            652.51|
|         CE|       501.94|       489.55|       513.83|            610.33|
+-----------+-------------+-------------+-------------+------------------+
only showing top 20 rows

In [ ]:
df_medias_treineiros = spark_df_clean.groupBy("IN_TREINEIRO").agg(
    round(avg("NU_NOTA_CH"), 2).alias("Media_Nota_CH"),
    round(avg("NU_NOTA_LC"), 2).alias("Media_Nota_LC"),
    round(avg("NU_NOTA_MT"), 2).alias("Media_Nota_MT"),
    round(avg("NU_NOTA_REDACAO"), 2).alias("Media_Nota_REDACAO")
)

df_medias_treineiros.show()

+------------+-------------+-------------+-------------+------------------+
|IN_TREINEIRO|Media_Nota_CH|Media_Nota_LC|Media_Nota_MT|Media_Nota_REDACAO|
+------------+-------------+-------------+-------------+------------------+
|           0|       526.49|       505.89|        534.3|            659.28|
|           1|       509.16|       498.06|       523.47|            629.46|
+------------+-------------+-------------+-------------+------------------+

In [ ]:
# Calcular a correlação entre as notas
corr_data = [
    ("NU_NOTA_CH", "NU_NOTA_LC"),
    ("NU_NOTA_CH", "NU_NOTA_MT"),
    ("NU_NOTA_CH", "NU_NOTA_REDACAO"),
    ("NU_NOTA_LC", "NU_NOTA_MT"),
    ("NU_NOTA_LC", "NU_NOTA_REDACAO"),
    ("NU_NOTA_MT", "NU_NOTA_REDACAO")
]

for col1, col2 in corr_data:
    corr_value = spark_df_clean.stat.corr(col1, col2)
    # Formatar para duas casas decimais durante a impressão
    print(f"Correlação entre {col1} e {col2}: {corr_value:.2f}")

Correlação entre NU_NOTA_CH e NU_NOTA_LC: 0.77
Correlação entre NU_NOTA_CH e NU_NOTA_MT: 0.65
Correlação entre NU_NOTA_CH e NU_NOTA_REDACAO: 0.53
Correlação entre NU_NOTA_LC e NU_NOTA_MT: 0.65
Correlação entre NU_NOTA_LC e NU_NOTA_REDACAO: 0.55
Correlação entre NU_NOTA_MT e NU_NOTA_REDACAO: 0.52